name: 152-frontend-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Times
        id:   time
        with:
          timeZone: 2
          format: 'YYYY-MM-DD-HH-mm-ss'
        uses: nanzm/get-time-action@v1.1

      - name: Checkout Rep
        uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.2

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier

      - name: build
        run: |
          npm prune
          npm run build --configuration=production

      - name: Run Test
        run: npm run test-no-watch

      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/223-frontend/*"
          tag: ${{steps.time.outputs.time}}
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "223-frontend"
